name: Release drafter

# Push events to every tag not containing "/"
on:
  push:
    tags:
      - "*"

jobs:
  draft-a-release:
    name: Draft a release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: |
          ./gradlew publishPublishMavenPublicationToLocalRepoRepository
      - name: Build shadowJar and include in artifacts
        run: |
          ./gradlew shadowJar
          JDBC_VERSION=$(./gradlew :properties | grep version | cut -d ' ' -f 2)
          SHADOW_JAR=$(echo build/libs/opensearch-sql-jdbc-shadow-"$JDBC_VERSION".jar)
          ARTIFACTS=$(echo build/repository/org/opensearch/driver/opensearch-sql-jdbc/"$JDBC_VERSION")
          mv $SHADOW_JAR $ARTIFACTS
      - name: Create artifacts tar
        run:
          tar -C build -cvf artifacts.tar.gz repository
      - name: Draft a release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: |
            artifacts.tar.gz
