name: SQL JDBC Java CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  build:
    name: Test tar packaging with shadowJar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle
      - name: publishToMavenLocal
        run:
          ./gradlew publishPublishMavenPublicationToLocalRepoRepository
      - name: Build shadowJar
        run:
          ./gradlew shadowJar
      - name: copy shadowJar to path
        run:
          cp build/libs/opensearch-sql-jdbc-shadow-1.4.0.0.jar ${HOME}/.m2/repository/org/opensearch/driver/opensearch-sql-jdbc/1.4.0.0
      - name: package tar
        run:
          tar -C build -cvf artifacts.tar.gz repository
      - name: Create Artifact Path
        run: |
          mkdir -p sql-jdbc-builds
          cp artifacts.tar.gz sql-jdbc-builds

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sql-jdbc
          path: sql-jdbc-builds
